language: node_js
node_js:
- stable
- '6'
- '4'
branches:
  only:
    - master
install:
- npm install
after_success:
- npx semantic-release
env:
  global:
  # NPM_TOKEN
  - secure: WS9j1Iom5XEso9DXRTUHTDJG/sbOAE+aegNRbPZny4igs3D5hNTNTh4QMg3eTFwjbZ9IHtFnRVVFMWekgm2aFqDcRDq/8SfF3ebfqJLnXy940zC+UtzxmckLhhuxs7zfRJl5U0UVptKvxTGqLsD7vd4kY0/66lki98QBKkZWbk+9zloxYX9Mt/0fuIdtBF7iBn+p7u+//hxQHGPRLEbhNT56vZEFmPf/CsOfr9/cv5pXDV2gOhZEFrFHIUZQ/oi+4xepD8ZwNKs+5TizyVMy+3S/TjBjmo4uoZFi2lpyEaP1JTjmDxvOp0UOhyCiMM+RqJbueq/scyNtMsrMuWKGB0WV/A2h3+V7QjlQqoSPkYags4MUDA0qpHQZNzpAFP35CVP4dO9H29XvDdZ0R2vURw85CbhxherSH8Ni3AmuHEHsKndJOIglH585dQfPTeyaReepkQqAKh+16w/pFqSMtBK8aW6sTVvngCmUDaF/9B3lpqMb10pTOwRaFNCjGzJFatwcf/xlwmX7HjMqNtYZTXOuVFzRihXjW5M93gC7NNHeltRgk9XbQlwuqimuvjQhZeVG5LIcYpexI4l/FfP7gA6zu7dRqmv2RSaATIY+0xgNNATkaI+CQl7UnfDk4oV0JcILhxR7/RSeDpzbMzo2cK7B81Fti3bBv1yaMfEPfjI=
  # GH_TOKEN
  - secure: RG4QDiYfb/2ioHpEYiVteTP+29xuHDQk8OU9BDqvCi/VPE0Au34hhWQmI7Ucen+jD/2bSj8l7yT8ncmiM1zgHGu0Uob4F3cafI+4K+d0B7/xb5qoc3HV0VDIqh5ANYMSTnIKWVmxQuB3j8y/x5QcFMmyu1hjJuZ6l5xCkWIpMoI/oXLfOP3gY58Lgy/H+lVfErNVbrvR48N6Sn1gD2QpVuowyIvDj7x04anyislRImoV7lLUMVwPKfwKXSi3CuGeu22PG5yxB4g7HC2KNptb3KJ8bSJPv9rfcLq+BfSHOcca3z5nIrRkX4AnuhI5JmaPvRHtyz8NWTKwwMOxsLOHgPY2zkqlKw68ttm1DiQPZbuaY5KlwmHo2YffQTLY6scPPyelIbhL9JDz+r5gbBBZYtLqE9qC3ljoIoHyQOOPzbcZzB4CjwO9FlLa5HqpgXCbr2qznNzp/KE4ExKZfVQTlsue9kQyTbQos9UMu9FhvvCZ67WMgFjd43FpXaVp3MHrOttfAeUPla+OvoalV3kbcKusqTS6uXRfd42zv+UCi3mAbufDmI71OfB+rjRTW8tSI0u3YbFFlqEbim4ZMFKsRSZ5+x/8ev7gegK0pDMN811MsAVmC/sJYZS+BrD47U8ECTkRK44IHrCCSTEEigd5vf/qOsPSCYVCZrHbm1svgXQ=
