language: node_js
node_js:
- stable
- '6'
- '4'
branches:
  only:
    - master
install:
- npm install
after_success:
- npx semantic-release
env:
  global:
  # NPM_TOKEN
  - secure: XzUPRw7XiYv97RnXtRZW9d+D32zWtpvSgQ3J3Q54BoRhbKrsmRhxg9atck3IZBq1bpAqdhO02zqIQBIZDdJOJv2tD+xHAyaL3k1KyQ5VOYrvnyg0rz6DkjXoxr/hbFL9KMVU1jMcNl05liM5D5HVU5zFNyIbIHn8YmEt38oCUrEx4esHjRFYXVSm7bsg5jR8Z6uZzA65YUgZPSr3seruGzCE7IfClA9exIZpOLy6hUaPPX7EGxa4S/qABmwh8a15N9/+Mxcjo3x3PLmnFdNrRs335rvZ35l8JZASljW1TMqGCL+ipBt7CEFZYS5UJ+8MOM4BMHndAx6h7zGeqgp/oqqciyXbzJiiJYX+AJPVuq7yB0//TfGI50NC5hbBow0KYkknYcZV9M9vSI7qUTmWbFAzV6NIWmz53K9fjh8lEc/nVGm1s1eam82ChQF0JQD8A95NoxrGLlYrKCJDOdinQx2UsqhRI282n/+GDqVmeU3kqpIvfOdkKbAeWePHlWAA1+4dRFJrblQgn/CANZsR4IODKqk9o10lOvlPU5n156HwFwGoML2YWTNaQRqK5iUgpohOdlKwiC+ELtr8S29YPE+c84Rxf+S5mBPL2n6aNvdqL5h1IcbUsofMSEAMypiu9LAc7nh+cqkX0hP+jpHM7J42oI0lixX53fdiVFYDOcs=
  # GH_TOKEN
  - secure: RG4QDiYfb/2ioHpEYiVteTP+29xuHDQk8OU9BDqvCi/VPE0Au34hhWQmI7Ucen+jD/2bSj8l7yT8ncmiM1zgHGu0Uob4F3cafI+4K+d0B7/xb5qoc3HV0VDIqh5ANYMSTnIKWVmxQuB3j8y/x5QcFMmyu1hjJuZ6l5xCkWIpMoI/oXLfOP3gY58Lgy/H+lVfErNVbrvR48N6Sn1gD2QpVuowyIvDj7x04anyislRImoV7lLUMVwPKfwKXSi3CuGeu22PG5yxB4g7HC2KNptb3KJ8bSJPv9rfcLq+BfSHOcca3z5nIrRkX4AnuhI5JmaPvRHtyz8NWTKwwMOxsLOHgPY2zkqlKw68ttm1DiQPZbuaY5KlwmHo2YffQTLY6scPPyelIbhL9JDz+r5gbBBZYtLqE9qC3ljoIoHyQOOPzbcZzB4CjwO9FlLa5HqpgXCbr2qznNzp/KE4ExKZfVQTlsue9kQyTbQos9UMu9FhvvCZ67WMgFjd43FpXaVp3MHrOttfAeUPla+OvoalV3kbcKusqTS6uXRfd42zv+UCi3mAbufDmI71OfB+rjRTW8tSI0u3YbFFlqEbim4ZMFKsRSZ5+x/8ev7gegK0pDMN811MsAVmC/sJYZS+BrD47U8ECTkRK44IHrCCSTEEigd5vf/qOsPSCYVCZrHbm1svgXQ=
